# Generated by Django 2.0.2 on 2020-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shagoappoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='alloted_duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='alloted_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
