# Generated by Django 2.0.2 on 2020-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shagoappoint', '0002_auto_20200716_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='OTP',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
