# Generated by Django 2.0.2 on 2020-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shagoappoint', '0003_appointment_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='OTP',
        ),
    ]
